// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.2
// source: proto/location.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocationService_PaligonCreate_FullMethodName = "/LocationService.LocationService/PaligonCreate"
	LocationService_PaligonDelete_FullMethodName = "/LocationService.LocationService/PaligonDelete"
	LocationService_PaligonList_FullMethodName   = "/LocationService.LocationService/PaligonList"
	LocationService_PointCreate_FullMethodName   = "/LocationService.LocationService/PointCreate"
	LocationService_PointDelete_FullMethodName   = "/LocationService.LocationService/PointDelete"
	LocationService_PointList_FullMethodName     = "/LocationService.LocationService/PointList"
	LocationService_DutyCreate_FullMethodName    = "/LocationService.LocationService/DutyCreate"
	LocationService_DutyStop_FullMethodName      = "/LocationService.LocationService/DutyStop"
	LocationService_DutyList_FullMethodName      = "/LocationService.LocationService/DutyList"
	LocationService_DutyInfo_FullMethodName      = "/LocationService.LocationService/DutyInfo"
	LocationService_Location_FullMethodName      = "/LocationService.LocationService/Location"
	LocationService_AlarmStream_FullMethodName   = "/LocationService.LocationService/AlarmStream"
)

// LocationServiceClient is the client API for LocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ───────────────── SERVICE ─────────────────
type LocationServiceClient interface {
	PaligonCreate(ctx context.Context, in *PaligonRequest, opts ...grpc.CallOption) (*PaligonResponse, error)
	PaligonDelete(ctx context.Context, in *PaligonDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
	PaligonList(ctx context.Context, in *PaligonFilterRequest, opts ...grpc.CallOption) (*PaligonListResponse, error)
	PointCreate(ctx context.Context, in *PointRequest, opts ...grpc.CallOption) (*PointResponse, error)
	PointDelete(ctx context.Context, in *PointDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
	PointList(ctx context.Context, in *PointListRequest, opts ...grpc.CallOption) (*PointListResponse, error)
	DutyCreate(ctx context.Context, in *DutyRequest, opts ...grpc.CallOption) (*DutyResponse, error)
	DutyStop(ctx context.Context, in *StopDutyRequest, opts ...grpc.CallOption) (*Empty, error)
	DutyList(ctx context.Context, in *DutyListRequest, opts ...grpc.CallOption) (*DutyListResponse, error)
	DutyInfo(ctx context.Context, in *DutyInfoRequest, opts ...grpc.CallOption) (*DutyInfoResponse, error)
	Location(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*Empty, error)
	AlarmStream(ctx context.Context, in *AlarmRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AlarmEvent], error)
}

type locationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocationServiceClient(cc grpc.ClientConnInterface) LocationServiceClient {
	return &locationServiceClient{cc}
}

func (c *locationServiceClient) PaligonCreate(ctx context.Context, in *PaligonRequest, opts ...grpc.CallOption) (*PaligonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaligonResponse)
	err := c.cc.Invoke(ctx, LocationService_PaligonCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) PaligonDelete(ctx context.Context, in *PaligonDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, LocationService_PaligonDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) PaligonList(ctx context.Context, in *PaligonFilterRequest, opts ...grpc.CallOption) (*PaligonListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaligonListResponse)
	err := c.cc.Invoke(ctx, LocationService_PaligonList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) PointCreate(ctx context.Context, in *PointRequest, opts ...grpc.CallOption) (*PointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PointResponse)
	err := c.cc.Invoke(ctx, LocationService_PointCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) PointDelete(ctx context.Context, in *PointDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, LocationService_PointDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) PointList(ctx context.Context, in *PointListRequest, opts ...grpc.CallOption) (*PointListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PointListResponse)
	err := c.cc.Invoke(ctx, LocationService_PointList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) DutyCreate(ctx context.Context, in *DutyRequest, opts ...grpc.CallOption) (*DutyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DutyResponse)
	err := c.cc.Invoke(ctx, LocationService_DutyCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) DutyStop(ctx context.Context, in *StopDutyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, LocationService_DutyStop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) DutyList(ctx context.Context, in *DutyListRequest, opts ...grpc.CallOption) (*DutyListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DutyListResponse)
	err := c.cc.Invoke(ctx, LocationService_DutyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) DutyInfo(ctx context.Context, in *DutyInfoRequest, opts ...grpc.CallOption) (*DutyInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DutyInfoResponse)
	err := c.cc.Invoke(ctx, LocationService_DutyInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) Location(ctx context.Context, in *LocationRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, LocationService_Location_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *locationServiceClient) AlarmStream(ctx context.Context, in *AlarmRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AlarmEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocationService_ServiceDesc.Streams[0], LocationService_AlarmStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AlarmRequest, AlarmEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocationService_AlarmStreamClient = grpc.ServerStreamingClient[AlarmEvent]

// LocationServiceServer is the server API for LocationService service.
// All implementations must embed UnimplementedLocationServiceServer
// for forward compatibility.
//
// ───────────────── SERVICE ─────────────────
type LocationServiceServer interface {
	PaligonCreate(context.Context, *PaligonRequest) (*PaligonResponse, error)
	PaligonDelete(context.Context, *PaligonDeleteRequest) (*Empty, error)
	PaligonList(context.Context, *PaligonFilterRequest) (*PaligonListResponse, error)
	PointCreate(context.Context, *PointRequest) (*PointResponse, error)
	PointDelete(context.Context, *PointDeleteRequest) (*Empty, error)
	PointList(context.Context, *PointListRequest) (*PointListResponse, error)
	DutyCreate(context.Context, *DutyRequest) (*DutyResponse, error)
	DutyStop(context.Context, *StopDutyRequest) (*Empty, error)
	DutyList(context.Context, *DutyListRequest) (*DutyListResponse, error)
	DutyInfo(context.Context, *DutyInfoRequest) (*DutyInfoResponse, error)
	Location(context.Context, *LocationRequest) (*Empty, error)
	AlarmStream(*AlarmRequest, grpc.ServerStreamingServer[AlarmEvent]) error
	mustEmbedUnimplementedLocationServiceServer()
}

// UnimplementedLocationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocationServiceServer struct{}

func (UnimplementedLocationServiceServer) PaligonCreate(context.Context, *PaligonRequest) (*PaligonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PaligonCreate not implemented")
}
func (UnimplementedLocationServiceServer) PaligonDelete(context.Context, *PaligonDeleteRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PaligonDelete not implemented")
}
func (UnimplementedLocationServiceServer) PaligonList(context.Context, *PaligonFilterRequest) (*PaligonListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PaligonList not implemented")
}
func (UnimplementedLocationServiceServer) PointCreate(context.Context, *PointRequest) (*PointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PointCreate not implemented")
}
func (UnimplementedLocationServiceServer) PointDelete(context.Context, *PointDeleteRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PointDelete not implemented")
}
func (UnimplementedLocationServiceServer) PointList(context.Context, *PointListRequest) (*PointListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PointList not implemented")
}
func (UnimplementedLocationServiceServer) DutyCreate(context.Context, *DutyRequest) (*DutyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DutyCreate not implemented")
}
func (UnimplementedLocationServiceServer) DutyStop(context.Context, *StopDutyRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DutyStop not implemented")
}
func (UnimplementedLocationServiceServer) DutyList(context.Context, *DutyListRequest) (*DutyListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DutyList not implemented")
}
func (UnimplementedLocationServiceServer) DutyInfo(context.Context, *DutyInfoRequest) (*DutyInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DutyInfo not implemented")
}
func (UnimplementedLocationServiceServer) Location(context.Context, *LocationRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Location not implemented")
}
func (UnimplementedLocationServiceServer) AlarmStream(*AlarmRequest, grpc.ServerStreamingServer[AlarmEvent]) error {
	return status.Error(codes.Unimplemented, "method AlarmStream not implemented")
}
func (UnimplementedLocationServiceServer) mustEmbedUnimplementedLocationServiceServer() {}
func (UnimplementedLocationServiceServer) testEmbeddedByValue()                         {}

// UnsafeLocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocationServiceServer will
// result in compilation errors.
type UnsafeLocationServiceServer interface {
	mustEmbedUnimplementedLocationServiceServer()
}

func RegisterLocationServiceServer(s grpc.ServiceRegistrar, srv LocationServiceServer) {
	// If the following call panics, it indicates UnimplementedLocationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocationService_ServiceDesc, srv)
}

func _LocationService_PaligonCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaligonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).PaligonCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_PaligonCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).PaligonCreate(ctx, req.(*PaligonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_PaligonDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaligonDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).PaligonDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_PaligonDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).PaligonDelete(ctx, req.(*PaligonDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_PaligonList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaligonFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).PaligonList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_PaligonList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).PaligonList(ctx, req.(*PaligonFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_PointCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).PointCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_PointCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).PointCreate(ctx, req.(*PointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_PointDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PointDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).PointDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_PointDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).PointDelete(ctx, req.(*PointDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_PointList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PointListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).PointList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_PointList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).PointList(ctx, req.(*PointListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_DutyCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DutyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).DutyCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_DutyCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).DutyCreate(ctx, req.(*DutyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_DutyStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopDutyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).DutyStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_DutyStop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).DutyStop(ctx, req.(*StopDutyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_DutyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DutyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).DutyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_DutyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).DutyList(ctx, req.(*DutyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_DutyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DutyInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).DutyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_DutyInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).DutyInfo(ctx, req.(*DutyInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_Location_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServiceServer).Location(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocationService_Location_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServiceServer).Location(ctx, req.(*LocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocationService_AlarmStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AlarmRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LocationServiceServer).AlarmStream(m, &grpc.GenericServerStream[AlarmRequest, AlarmEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocationService_AlarmStreamServer = grpc.ServerStreamingServer[AlarmEvent]

// LocationService_ServiceDesc is the grpc.ServiceDesc for LocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LocationService.LocationService",
	HandlerType: (*LocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PaligonCreate",
			Handler:    _LocationService_PaligonCreate_Handler,
		},
		{
			MethodName: "PaligonDelete",
			Handler:    _LocationService_PaligonDelete_Handler,
		},
		{
			MethodName: "PaligonList",
			Handler:    _LocationService_PaligonList_Handler,
		},
		{
			MethodName: "PointCreate",
			Handler:    _LocationService_PointCreate_Handler,
		},
		{
			MethodName: "PointDelete",
			Handler:    _LocationService_PointDelete_Handler,
		},
		{
			MethodName: "PointList",
			Handler:    _LocationService_PointList_Handler,
		},
		{
			MethodName: "DutyCreate",
			Handler:    _LocationService_DutyCreate_Handler,
		},
		{
			MethodName: "DutyStop",
			Handler:    _LocationService_DutyStop_Handler,
		},
		{
			MethodName: "DutyList",
			Handler:    _LocationService_DutyList_Handler,
		},
		{
			MethodName: "DutyInfo",
			Handler:    _LocationService_DutyInfo_Handler,
		},
		{
			MethodName: "Location",
			Handler:    _LocationService_Location_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AlarmStream",
			Handler:       _LocationService_AlarmStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/location.proto",
}
