// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: proto/location.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ───────────────── COMMON ─────────────────
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{0}
}

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Longitude     float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_proto_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{1}
}

func (x *Coordinate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Coordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

// ───────────────── PALIGON ─────────────────
type PaligonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RegionId      int32                  `protobuf:"varint,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	DistrictId    int32                  `protobuf:"varint,3,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	OrgId         int32                  `protobuf:"varint,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	BoundaryData  []*Coordinate          `protobuf:"bytes,5,rep,name=boundary_data,json=boundaryData,proto3" json:"boundary_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaligonRequest) Reset() {
	*x = PaligonRequest{}
	mi := &file_proto_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaligonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaligonRequest) ProtoMessage() {}

func (x *PaligonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaligonRequest.ProtoReflect.Descriptor instead.
func (*PaligonRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{2}
}

func (x *PaligonRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaligonRequest) GetRegionId() int32 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *PaligonRequest) GetDistrictId() int32 {
	if x != nil {
		return x.DistrictId
	}
	return 0
}

func (x *PaligonRequest) GetOrgId() int32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *PaligonRequest) GetBoundaryData() []*Coordinate {
	if x != nil {
		return x.BoundaryData
	}
	return nil
}

type PaligonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaligonResponse) Reset() {
	*x = PaligonResponse{}
	mi := &file_proto_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaligonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaligonResponse) ProtoMessage() {}

func (x *PaligonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaligonResponse.ProtoReflect.Descriptor instead.
func (*PaligonResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{3}
}

func (x *PaligonResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PaligonDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaligonDeleteRequest) Reset() {
	*x = PaligonDeleteRequest{}
	mi := &file_proto_location_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaligonDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaligonDeleteRequest) ProtoMessage() {}

func (x *PaligonDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaligonDeleteRequest.ProtoReflect.Descriptor instead.
func (*PaligonDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{4}
}

func (x *PaligonDeleteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PaligonFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	RegionId      *int32                 `protobuf:"varint,2,opt,name=region_id,json=regionId,proto3,oneof" json:"region_id,omitempty"`
	DistrictId    *int32                 `protobuf:"varint,3,opt,name=district_id,json=districtId,proto3,oneof" json:"district_id,omitempty"`
	OrgId         *int32                 `protobuf:"varint,4,opt,name=org_id,json=orgId,proto3,oneof" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaligonFilterRequest) Reset() {
	*x = PaligonFilterRequest{}
	mi := &file_proto_location_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaligonFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaligonFilterRequest) ProtoMessage() {}

func (x *PaligonFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaligonFilterRequest.ProtoReflect.Descriptor instead.
func (*PaligonFilterRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{5}
}

func (x *PaligonFilterRequest) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PaligonFilterRequest) GetRegionId() int32 {
	if x != nil && x.RegionId != nil {
		return *x.RegionId
	}
	return 0
}

func (x *PaligonFilterRequest) GetDistrictId() int32 {
	if x != nil && x.DistrictId != nil {
		return *x.DistrictId
	}
	return 0
}

func (x *PaligonFilterRequest) GetOrgId() int32 {
	if x != nil && x.OrgId != nil {
		return *x.OrgId
	}
	return 0
}

type PaligonListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paligons      []*PaligonRequest      `protobuf:"bytes,1,rep,name=paligons,proto3" json:"paligons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaligonListResponse) Reset() {
	*x = PaligonListResponse{}
	mi := &file_proto_location_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaligonListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaligonListResponse) ProtoMessage() {}

func (x *PaligonListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaligonListResponse.ProtoReflect.Descriptor instead.
func (*PaligonListResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{6}
}

func (x *PaligonListResponse) GetPaligons() []*PaligonRequest {
	if x != nil {
		return x.Paligons
	}
	return nil
}

// ───────────────── POINT ─────────────────
type PointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PaligonId     int32                  `protobuf:"varint,2,opt,name=paligon_id,json=paligonId,proto3" json:"paligon_id,omitempty"`
	Order         int32                  `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	Radius        int32                  `protobuf:"varint,4,opt,name=radius,proto3" json:"radius,omitempty"`
	Latitude      float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	StartTime     string                 `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // "HH:MM:SS"
	EndTime       string                 `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // "HH:MM:SS"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointRequest) Reset() {
	*x = PointRequest{}
	mi := &file_proto_location_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointRequest) ProtoMessage() {}

func (x *PointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointRequest.ProtoReflect.Descriptor instead.
func (*PointRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{7}
}

func (x *PointRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PointRequest) GetPaligonId() int32 {
	if x != nil {
		return x.PaligonId
	}
	return 0
}

func (x *PointRequest) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *PointRequest) GetRadius() int32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *PointRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *PointRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *PointRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *PointRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type PointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointResponse) Reset() {
	*x = PointResponse{}
	mi := &file_proto_location_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointResponse) ProtoMessage() {}

func (x *PointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointResponse.ProtoReflect.Descriptor instead.
func (*PointResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{8}
}

func (x *PointResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PointDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointDeleteRequest) Reset() {
	*x = PointDeleteRequest{}
	mi := &file_proto_location_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointDeleteRequest) ProtoMessage() {}

func (x *PointDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointDeleteRequest.ProtoReflect.Descriptor instead.
func (*PointDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{9}
}

func (x *PointDeleteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PointListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaligonId     *int32                 `protobuf:"varint,1,opt,name=paligon_id,json=paligonId,proto3,oneof" json:"paligon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointListRequest) Reset() {
	*x = PointListRequest{}
	mi := &file_proto_location_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointListRequest) ProtoMessage() {}

func (x *PointListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointListRequest.ProtoReflect.Descriptor instead.
func (*PointListRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{10}
}

func (x *PointListRequest) GetPaligonId() int32 {
	if x != nil && x.PaligonId != nil {
		return *x.PaligonId
	}
	return 0
}

type PointListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*PointRequest        `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointListResponse) Reset() {
	*x = PointListResponse{}
	mi := &file_proto_location_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointListResponse) ProtoMessage() {}

func (x *PointListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointListResponse.ProtoReflect.Descriptor instead.
func (*PointListResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{11}
}

func (x *PointListResponse) GetPoints() []*PointRequest {
	if x != nil {
		return x.Points
	}
	return nil
}

// ───────────────── DUTY ─────────────────
type Assignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaligonId     int32                  `protobuf:"varint,1,opt,name=paligon_id,json=paligonId,proto3" json:"paligon_id,omitempty"`
	Employees     []string               `protobuf:"bytes,2,rep,name=employees,proto3" json:"employees,omitempty"` // pinfl_hash list
	Vehicles      []string               `protobuf:"bytes,3,rep,name=vehicles,proto3" json:"vehicles,omitempty"`   // davlat raqami, e.g. "01A23BC"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_proto_location_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{12}
}

func (x *Assignment) GetPaligonId() int32 {
	if x != nil {
		return x.PaligonId
	}
	return 0
}

func (x *Assignment) GetEmployees() []string {
	if x != nil {
		return x.Employees
	}
	return nil
}

func (x *Assignment) GetVehicles() []string {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

type DutyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     int32                  `protobuf:"varint,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	StartedAt     string                 `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"` // ISO 8601
	OrgId         int32                  `protobuf:"varint,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	RegionId      int32                  `protobuf:"varint,4,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	DistrictId    int32                  `protobuf:"varint,5,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	Assignments   []*Assignment          `protobuf:"bytes,6,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DutyRequest) Reset() {
	*x = DutyRequest{}
	mi := &file_proto_location_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DutyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DutyRequest) ProtoMessage() {}

func (x *DutyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DutyRequest.ProtoReflect.Descriptor instead.
func (*DutyRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{13}
}

func (x *DutyRequest) GetSectionId() int32 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *DutyRequest) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *DutyRequest) GetOrgId() int32 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *DutyRequest) GetRegionId() int32 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *DutyRequest) GetDistrictId() int32 {
	if x != nil {
		return x.DistrictId
	}
	return 0
}

func (x *DutyRequest) GetAssignments() []*Assignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type DutyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DutyResponse) Reset() {
	*x = DutyResponse{}
	mi := &file_proto_location_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DutyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DutyResponse) ProtoMessage() {}

func (x *DutyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DutyResponse.ProtoReflect.Descriptor instead.
func (*DutyResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{14}
}

func (x *DutyResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StopDutyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     int32                  `protobuf:"varint,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	EndedAt       string                 `protobuf:"bytes,2,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"` // ISO 8601
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDutyRequest) Reset() {
	*x = StopDutyRequest{}
	mi := &file_proto_location_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDutyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDutyRequest) ProtoMessage() {}

func (x *StopDutyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDutyRequest.ProtoReflect.Descriptor instead.
func (*StopDutyRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{15}
}

func (x *StopDutyRequest) GetSectionId() int32 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *StopDutyRequest) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

type DutyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     *int32                 `protobuf:"varint,1,opt,name=section_id,json=sectionId,proto3,oneof" json:"section_id,omitempty"`
	StartedAt     *string                `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	OrgId         *int32                 `protobuf:"varint,3,opt,name=org_id,json=orgId,proto3,oneof" json:"org_id,omitempty"`
	RegionId      *int32                 `protobuf:"varint,4,opt,name=region_id,json=regionId,proto3,oneof" json:"region_id,omitempty"`
	DistrictId    *int32                 `protobuf:"varint,5,opt,name=district_id,json=districtId,proto3,oneof" json:"district_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DutyListRequest) Reset() {
	*x = DutyListRequest{}
	mi := &file_proto_location_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DutyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DutyListRequest) ProtoMessage() {}

func (x *DutyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DutyListRequest.ProtoReflect.Descriptor instead.
func (*DutyListRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{16}
}

func (x *DutyListRequest) GetSectionId() int32 {
	if x != nil && x.SectionId != nil {
		return *x.SectionId
	}
	return 0
}

func (x *DutyListRequest) GetStartedAt() string {
	if x != nil && x.StartedAt != nil {
		return *x.StartedAt
	}
	return ""
}

func (x *DutyListRequest) GetOrgId() int32 {
	if x != nil && x.OrgId != nil {
		return *x.OrgId
	}
	return 0
}

func (x *DutyListRequest) GetRegionId() int32 {
	if x != nil && x.RegionId != nil {
		return *x.RegionId
	}
	return 0
}

func (x *DutyListRequest) GetDistrictId() int32 {
	if x != nil && x.DistrictId != nil {
		return *x.DistrictId
	}
	return 0
}

type DutyListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duties        []*DutyRequest         `protobuf:"bytes,1,rep,name=duties,proto3" json:"duties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DutyListResponse) Reset() {
	*x = DutyListResponse{}
	mi := &file_proto_location_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DutyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DutyListResponse) ProtoMessage() {}

func (x *DutyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DutyListResponse.ProtoReflect.Descriptor instead.
func (*DutyListResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{17}
}

func (x *DutyListResponse) GetDuties() []*DutyRequest {
	if x != nil {
		return x.Duties
	}
	return nil
}

// ───────────────── LOCATION ─────────────────
type LocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PinflHash     string                 `protobuf:"bytes,1,opt,name=pinfl_hash,json=pinflHash,proto3" json:"pinfl_hash,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,4,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationRequest) Reset() {
	*x = LocationRequest{}
	mi := &file_proto_location_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationRequest) ProtoMessage() {}

func (x *LocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationRequest.ProtoReflect.Descriptor instead.
func (*LocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{18}
}

func (x *LocationRequest) GetPinflHash() string {
	if x != nil {
		return x.PinflHash
	}
	return ""
}

func (x *LocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LocationRequest) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *LocationRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ───────────────── DUTY INFO ─────────────────
type DutyInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     int32                  `protobuf:"varint,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DutyInfoRequest) Reset() {
	*x = DutyInfoRequest{}
	mi := &file_proto_location_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DutyInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DutyInfoRequest) ProtoMessage() {}

func (x *DutyInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DutyInfoRequest.ProtoReflect.Descriptor instead.
func (*DutyInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{19}
}

func (x *DutyInfoRequest) GetSectionId() int32 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

type EmployeeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PinflHash     string                 `protobuf:"bytes,1,opt,name=pinfl_hash,json=pinflHash,proto3" json:"pinfl_hash,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	InPolygon     bool                   `protobuf:"varint,4,opt,name=in_polygon,json=inPolygon,proto3" json:"in_polygon,omitempty"`
	AtPoint       bool                   `protobuf:"varint,5,opt,name=at_point,json=atPoint,proto3" json:"at_point,omitempty"`
	PointId       int32                  `protobuf:"varint,6,opt,name=point_id,json=pointId,proto3" json:"point_id,omitempty"`       // -1 = hech qaysi pointda emas
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeInfo) Reset() {
	*x = EmployeeInfo{}
	mi := &file_proto_location_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeInfo) ProtoMessage() {}

func (x *EmployeeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeInfo.ProtoReflect.Descriptor instead.
func (*EmployeeInfo) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{20}
}

func (x *EmployeeInfo) GetPinflHash() string {
	if x != nil {
		return x.PinflHash
	}
	return ""
}

func (x *EmployeeInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *EmployeeInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *EmployeeInfo) GetInPolygon() bool {
	if x != nil {
		return x.InPolygon
	}
	return false
}

func (x *EmployeeInfo) GetAtPoint() bool {
	if x != nil {
		return x.AtPoint
	}
	return false
}

func (x *EmployeeInfo) GetPointId() int32 {
	if x != nil {
		return x.PointId
	}
	return 0
}

func (x *EmployeeInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type VehicleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlateNumber   string                 `protobuf:"bytes,1,opt,name=plate_number,json=plateNumber,proto3" json:"plate_number,omitempty"` // davlat raqami, e.g. "01A23BC"
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	InPolygon     bool                   `protobuf:"varint,4,opt,name=in_polygon,json=inPolygon,proto3" json:"in_polygon,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleInfo) Reset() {
	*x = VehicleInfo{}
	mi := &file_proto_location_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleInfo) ProtoMessage() {}

func (x *VehicleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleInfo.ProtoReflect.Descriptor instead.
func (*VehicleInfo) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{21}
}

func (x *VehicleInfo) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

func (x *VehicleInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *VehicleInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *VehicleInfo) GetInPolygon() bool {
	if x != nil {
		return x.InPolygon
	}
	return false
}

func (x *VehicleInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type AssignmentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaligonId     int32                  `protobuf:"varint,1,opt,name=paligon_id,json=paligonId,proto3" json:"paligon_id,omitempty"`
	Employees     []*EmployeeInfo        `protobuf:"bytes,2,rep,name=employees,proto3" json:"employees,omitempty"`
	Vehicles      []*VehicleInfo         `protobuf:"bytes,3,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignmentInfo) Reset() {
	*x = AssignmentInfo{}
	mi := &file_proto_location_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentInfo) ProtoMessage() {}

func (x *AssignmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentInfo.ProtoReflect.Descriptor instead.
func (*AssignmentInfo) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{22}
}

func (x *AssignmentInfo) GetPaligonId() int32 {
	if x != nil {
		return x.PaligonId
	}
	return 0
}

func (x *AssignmentInfo) GetEmployees() []*EmployeeInfo {
	if x != nil {
		return x.Employees
	}
	return nil
}

func (x *AssignmentInfo) GetVehicles() []*VehicleInfo {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

type DutyInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     int32                  `protobuf:"varint,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Assignments   []*AssignmentInfo      `protobuf:"bytes,2,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DutyInfoResponse) Reset() {
	*x = DutyInfoResponse{}
	mi := &file_proto_location_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DutyInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DutyInfoResponse) ProtoMessage() {}

func (x *DutyInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DutyInfoResponse.ProtoReflect.Descriptor instead.
func (*DutyInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{23}
}

func (x *DutyInfoResponse) GetSectionId() int32 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *DutyInfoResponse) GetAssignments() []*AssignmentInfo {
	if x != nil {
		return x.Assignments
	}
	return nil
}

// ───────────────── ALARM ─────────────────
type AlarmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     int32                  `protobuf:"varint,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlarmRequest) Reset() {
	*x = AlarmRequest{}
	mi := &file_proto_location_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmRequest) ProtoMessage() {}

func (x *AlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmRequest.ProtoReflect.Descriptor instead.
func (*AlarmRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{24}
}

func (x *AlarmRequest) GetSectionId() int32 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

type AlarmEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SectionId int32                  `protobuf:"varint,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Type      string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // OUT_OF_POLYGON | POINT_MISSED
	PaligonId int32                  `protobuf:"varint,3,opt,name=paligon_id,json=paligonId,proto3" json:"paligon_id,omitempty"`
	PointId   int32                  `protobuf:"varint,4,opt,name=point_id,json=pointId,proto3" json:"point_id,omitempty"` // faqat POINT_MISSED uchun, aks holda 0
	Latitude  float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Message   string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix milliseconds
	// Types that are valid to be assigned to Subject:
	//
	//	*AlarmEvent_PinflHash
	//	*AlarmEvent_PlateNumber
	Subject       isAlarmEvent_Subject `protobuf_oneof:"subject"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlarmEvent) Reset() {
	*x = AlarmEvent{}
	mi := &file_proto_location_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmEvent) ProtoMessage() {}

func (x *AlarmEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmEvent.ProtoReflect.Descriptor instead.
func (*AlarmEvent) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{25}
}

func (x *AlarmEvent) GetSectionId() int32 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *AlarmEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AlarmEvent) GetPaligonId() int32 {
	if x != nil {
		return x.PaligonId
	}
	return 0
}

func (x *AlarmEvent) GetPointId() int32 {
	if x != nil {
		return x.PointId
	}
	return 0
}

func (x *AlarmEvent) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AlarmEvent) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *AlarmEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AlarmEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AlarmEvent) GetSubject() isAlarmEvent_Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *AlarmEvent) GetPinflHash() string {
	if x != nil {
		if x, ok := x.Subject.(*AlarmEvent_PinflHash); ok {
			return x.PinflHash
		}
	}
	return ""
}

func (x *AlarmEvent) GetPlateNumber() string {
	if x != nil {
		if x, ok := x.Subject.(*AlarmEvent_PlateNumber); ok {
			return x.PlateNumber
		}
	}
	return ""
}

type isAlarmEvent_Subject interface {
	isAlarmEvent_Subject()
}

type AlarmEvent_PinflHash struct {
	PinflHash string `protobuf:"bytes,9,opt,name=pinfl_hash,json=pinflHash,proto3,oneof"` // xodim
}

type AlarmEvent_PlateNumber struct {
	PlateNumber string `protobuf:"bytes,10,opt,name=plate_number,json=plateNumber,proto3,oneof"` // transport vositasi
}

func (*AlarmEvent_PinflHash) isAlarmEvent_Subject() {}

func (*AlarmEvent_PlateNumber) isAlarmEvent_Subject() {}

var File_proto_location_proto protoreflect.FileDescriptor

const file_proto_location_proto_rawDesc = "" +
	"\n" +
	"\x14proto/location.proto\x12\x0fLocationService\"\a\n" +
	"\x05Empty\"F\n" +
	"\n" +
	"Coordinate\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\"\xb7\x01\n" +
	"\x0ePaligonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tregion_id\x18\x02 \x01(\x05R\bregionId\x12\x1f\n" +
	"\vdistrict_id\x18\x03 \x01(\x05R\n" +
	"districtId\x12\x15\n" +
	"\x06org_id\x18\x04 \x01(\x05R\x05orgId\x12@\n" +
	"\rboundary_data\x18\x05 \x03(\v2\x1b.LocationService.CoordinateR\fboundaryData\"!\n" +
	"\x0fPaligonResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"&\n" +
	"\x14PaligonDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xbf\x01\n" +
	"\x14PaligonFilterRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x05H\x00R\x02id\x88\x01\x01\x12 \n" +
	"\tregion_id\x18\x02 \x01(\x05H\x01R\bregionId\x88\x01\x01\x12$\n" +
	"\vdistrict_id\x18\x03 \x01(\x05H\x02R\n" +
	"districtId\x88\x01\x01\x12\x1a\n" +
	"\x06org_id\x18\x04 \x01(\x05H\x03R\x05orgId\x88\x01\x01B\x05\n" +
	"\x03_idB\f\n" +
	"\n" +
	"_region_idB\x0e\n" +
	"\f_district_idB\t\n" +
	"\a_org_id\"R\n" +
	"\x13PaligonListResponse\x12;\n" +
	"\bpaligons\x18\x01 \x03(\v2\x1f.LocationService.PaligonRequestR\bpaligons\"\xdf\x01\n" +
	"\fPointRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"paligon_id\x18\x02 \x01(\x05R\tpaligonId\x12\x14\n" +
	"\x05order\x18\x03 \x01(\x05R\x05order\x12\x16\n" +
	"\x06radius\x18\x04 \x01(\x05R\x06radius\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\b \x01(\tR\aendTime\"\x1f\n" +
	"\rPointResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"$\n" +
	"\x12PointDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"E\n" +
	"\x10PointListRequest\x12\"\n" +
	"\n" +
	"paligon_id\x18\x01 \x01(\x05H\x00R\tpaligonId\x88\x01\x01B\r\n" +
	"\v_paligon_id\"J\n" +
	"\x11PointListResponse\x125\n" +
	"\x06points\x18\x01 \x03(\v2\x1d.LocationService.PointRequestR\x06points\"e\n" +
	"\n" +
	"Assignment\x12\x1d\n" +
	"\n" +
	"paligon_id\x18\x01 \x01(\x05R\tpaligonId\x12\x1c\n" +
	"\temployees\x18\x02 \x03(\tR\temployees\x12\x1a\n" +
	"\bvehicles\x18\x03 \x03(\tR\bvehicles\"\xdf\x01\n" +
	"\vDutyRequest\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\x05R\tsectionId\x12\x1d\n" +
	"\n" +
	"started_at\x18\x02 \x01(\tR\tstartedAt\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\x05R\x05orgId\x12\x1b\n" +
	"\tregion_id\x18\x04 \x01(\x05R\bregionId\x12\x1f\n" +
	"\vdistrict_id\x18\x05 \x01(\x05R\n" +
	"districtId\x12=\n" +
	"\vassignments\x18\x06 \x03(\v2\x1b.LocationService.AssignmentR\vassignments\"\x1e\n" +
	"\fDutyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"K\n" +
	"\x0fStopDutyRequest\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\x05R\tsectionId\x12\x19\n" +
	"\bended_at\x18\x02 \x01(\tR\aendedAt\"\x84\x02\n" +
	"\x0fDutyListRequest\x12\"\n" +
	"\n" +
	"section_id\x18\x01 \x01(\x05H\x00R\tsectionId\x88\x01\x01\x12\"\n" +
	"\n" +
	"started_at\x18\x02 \x01(\tH\x01R\tstartedAt\x88\x01\x01\x12\x1a\n" +
	"\x06org_id\x18\x03 \x01(\x05H\x02R\x05orgId\x88\x01\x01\x12 \n" +
	"\tregion_id\x18\x04 \x01(\x05H\x03R\bregionId\x88\x01\x01\x12$\n" +
	"\vdistrict_id\x18\x05 \x01(\x05H\x04R\n" +
	"districtId\x88\x01\x01B\r\n" +
	"\v_section_idB\r\n" +
	"\v_started_atB\t\n" +
	"\a_org_idB\f\n" +
	"\n" +
	"_region_idB\x0e\n" +
	"\f_district_id\"H\n" +
	"\x10DutyListResponse\x124\n" +
	"\x06duties\x18\x01 \x03(\v2\x1c.LocationService.DutyRequestR\x06duties\"\xa4\x01\n" +
	"\x0fLocationRequest\x12\x1d\n" +
	"\n" +
	"pinfl_hash\x18\x01 \x01(\tR\tpinflHash\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baccuracy\x18\x04 \x01(\x01R\baccuracy\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"0\n" +
	"\x0fDutyInfoRequest\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\x05R\tsectionId\"\xdb\x01\n" +
	"\fEmployeeInfo\x12\x1d\n" +
	"\n" +
	"pinfl_hash\x18\x01 \x01(\tR\tpinflHash\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1d\n" +
	"\n" +
	"in_polygon\x18\x04 \x01(\bR\tinPolygon\x12\x19\n" +
	"\bat_point\x18\x05 \x01(\bR\aatPoint\x12\x19\n" +
	"\bpoint_id\x18\x06 \x01(\x05R\apointId\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"\xa8\x01\n" +
	"\vVehicleInfo\x12!\n" +
	"\fplate_number\x18\x01 \x01(\tR\vplateNumber\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1d\n" +
	"\n" +
	"in_polygon\x18\x04 \x01(\bR\tinPolygon\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"\xa6\x01\n" +
	"\x0eAssignmentInfo\x12\x1d\n" +
	"\n" +
	"paligon_id\x18\x01 \x01(\x05R\tpaligonId\x12;\n" +
	"\temployees\x18\x02 \x03(\v2\x1d.LocationService.EmployeeInfoR\temployees\x128\n" +
	"\bvehicles\x18\x03 \x03(\v2\x1c.LocationService.VehicleInfoR\bvehicles\"t\n" +
	"\x10DutyInfoResponse\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\x05R\tsectionId\x12A\n" +
	"\vassignments\x18\x02 \x03(\v2\x1f.LocationService.AssignmentInfoR\vassignments\"-\n" +
	"\fAlarmRequest\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\x05R\tsectionId\"\xbc\x02\n" +
	"\n" +
	"AlarmEvent\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\x05R\tsectionId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"paligon_id\x18\x03 \x01(\x05R\tpaligonId\x12\x19\n" +
	"\bpoint_id\x18\x04 \x01(\x05R\apointId\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\n" +
	"pinfl_hash\x18\t \x01(\tH\x00R\tpinflHash\x12#\n" +
	"\fplate_number\x18\n" +
	" \x01(\tH\x00R\vplateNumberB\t\n" +
	"\asubject2\xc5\a\n" +
	"\x0fLocationService\x12R\n" +
	"\rPaligonCreate\x12\x1f.LocationService.PaligonRequest\x1a .LocationService.PaligonResponse\x12N\n" +
	"\rPaligonDelete\x12%.LocationService.PaligonDeleteRequest\x1a\x16.LocationService.Empty\x12Z\n" +
	"\vPaligonList\x12%.LocationService.PaligonFilterRequest\x1a$.LocationService.PaligonListResponse\x12L\n" +
	"\vPointCreate\x12\x1d.LocationService.PointRequest\x1a\x1e.LocationService.PointResponse\x12J\n" +
	"\vPointDelete\x12#.LocationService.PointDeleteRequest\x1a\x16.LocationService.Empty\x12R\n" +
	"\tPointList\x12!.LocationService.PointListRequest\x1a\".LocationService.PointListResponse\x12I\n" +
	"\n" +
	"DutyCreate\x12\x1c.LocationService.DutyRequest\x1a\x1d.LocationService.DutyResponse\x12D\n" +
	"\bDutyStop\x12 .LocationService.StopDutyRequest\x1a\x16.LocationService.Empty\x12O\n" +
	"\bDutyList\x12 .LocationService.DutyListRequest\x1a!.LocationService.DutyListResponse\x12O\n" +
	"\bDutyInfo\x12 .LocationService.DutyInfoRequest\x1a!.LocationService.DutyInfoResponse\x12D\n" +
	"\bLocation\x12 .LocationService.LocationRequest\x1a\x16.LocationService.Empty\x12K\n" +
	"\vAlarmStream\x12\x1d.LocationService.AlarmRequest\x1a\x1b.LocationService.AlarmEvent0\x01B\x1dZ\x1bLocationService/proto;protob\x06proto3"

var (
	file_proto_location_proto_rawDescOnce sync.Once
	file_proto_location_proto_rawDescData []byte
)

func file_proto_location_proto_rawDescGZIP() []byte {
	file_proto_location_proto_rawDescOnce.Do(func() {
		file_proto_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_location_proto_rawDesc), len(file_proto_location_proto_rawDesc)))
	})
	return file_proto_location_proto_rawDescData
}

var file_proto_location_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_location_proto_goTypes = []any{
	(*Empty)(nil),                // 0: LocationService.Empty
	(*Coordinate)(nil),           // 1: LocationService.Coordinate
	(*PaligonRequest)(nil),       // 2: LocationService.PaligonRequest
	(*PaligonResponse)(nil),      // 3: LocationService.PaligonResponse
	(*PaligonDeleteRequest)(nil), // 4: LocationService.PaligonDeleteRequest
	(*PaligonFilterRequest)(nil), // 5: LocationService.PaligonFilterRequest
	(*PaligonListResponse)(nil),  // 6: LocationService.PaligonListResponse
	(*PointRequest)(nil),         // 7: LocationService.PointRequest
	(*PointResponse)(nil),        // 8: LocationService.PointResponse
	(*PointDeleteRequest)(nil),   // 9: LocationService.PointDeleteRequest
	(*PointListRequest)(nil),     // 10: LocationService.PointListRequest
	(*PointListResponse)(nil),    // 11: LocationService.PointListResponse
	(*Assignment)(nil),           // 12: LocationService.Assignment
	(*DutyRequest)(nil),          // 13: LocationService.DutyRequest
	(*DutyResponse)(nil),         // 14: LocationService.DutyResponse
	(*StopDutyRequest)(nil),      // 15: LocationService.StopDutyRequest
	(*DutyListRequest)(nil),      // 16: LocationService.DutyListRequest
	(*DutyListResponse)(nil),     // 17: LocationService.DutyListResponse
	(*LocationRequest)(nil),      // 18: LocationService.LocationRequest
	(*DutyInfoRequest)(nil),      // 19: LocationService.DutyInfoRequest
	(*EmployeeInfo)(nil),         // 20: LocationService.EmployeeInfo
	(*VehicleInfo)(nil),          // 21: LocationService.VehicleInfo
	(*AssignmentInfo)(nil),       // 22: LocationService.AssignmentInfo
	(*DutyInfoResponse)(nil),     // 23: LocationService.DutyInfoResponse
	(*AlarmRequest)(nil),         // 24: LocationService.AlarmRequest
	(*AlarmEvent)(nil),           // 25: LocationService.AlarmEvent
}
var file_proto_location_proto_depIdxs = []int32{
	1,  // 0: LocationService.PaligonRequest.boundary_data:type_name -> LocationService.Coordinate
	2,  // 1: LocationService.PaligonListResponse.paligons:type_name -> LocationService.PaligonRequest
	7,  // 2: LocationService.PointListResponse.points:type_name -> LocationService.PointRequest
	12, // 3: LocationService.DutyRequest.assignments:type_name -> LocationService.Assignment
	13, // 4: LocationService.DutyListResponse.duties:type_name -> LocationService.DutyRequest
	20, // 5: LocationService.AssignmentInfo.employees:type_name -> LocationService.EmployeeInfo
	21, // 6: LocationService.AssignmentInfo.vehicles:type_name -> LocationService.VehicleInfo
	22, // 7: LocationService.DutyInfoResponse.assignments:type_name -> LocationService.AssignmentInfo
	2,  // 8: LocationService.LocationService.PaligonCreate:input_type -> LocationService.PaligonRequest
	4,  // 9: LocationService.LocationService.PaligonDelete:input_type -> LocationService.PaligonDeleteRequest
	5,  // 10: LocationService.LocationService.PaligonList:input_type -> LocationService.PaligonFilterRequest
	7,  // 11: LocationService.LocationService.PointCreate:input_type -> LocationService.PointRequest
	9,  // 12: LocationService.LocationService.PointDelete:input_type -> LocationService.PointDeleteRequest
	10, // 13: LocationService.LocationService.PointList:input_type -> LocationService.PointListRequest
	13, // 14: LocationService.LocationService.DutyCreate:input_type -> LocationService.DutyRequest
	15, // 15: LocationService.LocationService.DutyStop:input_type -> LocationService.StopDutyRequest
	16, // 16: LocationService.LocationService.DutyList:input_type -> LocationService.DutyListRequest
	19, // 17: LocationService.LocationService.DutyInfo:input_type -> LocationService.DutyInfoRequest
	18, // 18: LocationService.LocationService.Location:input_type -> LocationService.LocationRequest
	24, // 19: LocationService.LocationService.AlarmStream:input_type -> LocationService.AlarmRequest
	3,  // 20: LocationService.LocationService.PaligonCreate:output_type -> LocationService.PaligonResponse
	0,  // 21: LocationService.LocationService.PaligonDelete:output_type -> LocationService.Empty
	6,  // 22: LocationService.LocationService.PaligonList:output_type -> LocationService.PaligonListResponse
	8,  // 23: LocationService.LocationService.PointCreate:output_type -> LocationService.PointResponse
	0,  // 24: LocationService.LocationService.PointDelete:output_type -> LocationService.Empty
	11, // 25: LocationService.LocationService.PointList:output_type -> LocationService.PointListResponse
	14, // 26: LocationService.LocationService.DutyCreate:output_type -> LocationService.DutyResponse
	0,  // 27: LocationService.LocationService.DutyStop:output_type -> LocationService.Empty
	17, // 28: LocationService.LocationService.DutyList:output_type -> LocationService.DutyListResponse
	23, // 29: LocationService.LocationService.DutyInfo:output_type -> LocationService.DutyInfoResponse
	0,  // 30: LocationService.LocationService.Location:output_type -> LocationService.Empty
	25, // 31: LocationService.LocationService.AlarmStream:output_type -> LocationService.AlarmEvent
	20, // [20:32] is the sub-list for method output_type
	8,  // [8:20] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_location_proto_init() }
func file_proto_location_proto_init() {
	if File_proto_location_proto != nil {
		return
	}
	file_proto_location_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_location_proto_msgTypes[10].OneofWrappers = []any{}
	file_proto_location_proto_msgTypes[16].OneofWrappers = []any{}
	file_proto_location_proto_msgTypes[25].OneofWrappers = []any{
		(*AlarmEvent_PinflHash)(nil),
		(*AlarmEvent_PlateNumber)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_location_proto_rawDesc), len(file_proto_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_location_proto_goTypes,
		DependencyIndexes: file_proto_location_proto_depIdxs,
		MessageInfos:      file_proto_location_proto_msgTypes,
	}.Build()
	File_proto_location_proto = out.File
	file_proto_location_proto_goTypes = nil
	file_proto_location_proto_depIdxs = nil
}
