# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import location_service_pb2 as location__service__pb2


class LocationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PaligonCreate = channel.unary_unary(
                '/LocationService.LocationService/PaligonCreate',
                request_serializer=location__service__pb2.PaligonRequest.SerializeToString,
                response_deserializer=location__service__pb2.PaligonResponse.FromString,
                )
        self.PaligonDelete = channel.unary_unary(
                '/LocationService.LocationService/PaligonDelete',
                request_serializer=location__service__pb2.PaligonDeleteRequest.SerializeToString,
                response_deserializer=location__service__pb2.Empty.FromString,
                )
        self.PaligonList = channel.unary_unary(
                '/LocationService.LocationService/PaligonList',
                request_serializer=location__service__pb2.PaligonFilterRequest.SerializeToString,
                response_deserializer=location__service__pb2.PaligonListResponse.FromString,
                )
        self.PointCreate = channel.unary_unary(
                '/LocationService.LocationService/PointCreate',
                request_serializer=location__service__pb2.PointRequest.SerializeToString,
                response_deserializer=location__service__pb2.PointResponse.FromString,
                )
        self.PointDelete = channel.unary_unary(
                '/LocationService.LocationService/PointDelete',
                request_serializer=location__service__pb2.PointDeleteRequest.SerializeToString,
                response_deserializer=location__service__pb2.Empty.FromString,
                )
        self.PointList = channel.unary_unary(
                '/LocationService.LocationService/PointList',
                request_serializer=location__service__pb2.PointListRequest.SerializeToString,
                response_deserializer=location__service__pb2.PointListResponse.FromString,
                )
        self.DutyCreate = channel.unary_unary(
                '/LocationService.LocationService/DutyCreate',
                request_serializer=location__service__pb2.DutyRequest.SerializeToString,
                response_deserializer=location__service__pb2.DutyResponse.FromString,
                )
        self.DutyStop = channel.unary_unary(
                '/LocationService.LocationService/DutyStop',
                request_serializer=location__service__pb2.StopDutyRequest.SerializeToString,
                response_deserializer=location__service__pb2.Empty.FromString,
                )
        self.DutyList = channel.unary_unary(
                '/LocationService.LocationService/DutyList',
                request_serializer=location__service__pb2.DutyListRequest.SerializeToString,
                response_deserializer=location__service__pb2.DutyListResponse.FromString,
                )
        self.DutyInfo = channel.unary_unary(
                '/LocationService.LocationService/DutyInfo',
                request_serializer=location__service__pb2.DutyInfoRequest.SerializeToString,
                response_deserializer=location__service__pb2.DutyInfoResponse.FromString,
                )
        self.Location = channel.unary_unary(
                '/LocationService.LocationService/Location',
                request_serializer=location__service__pb2.LocationRequest.SerializeToString,
                response_deserializer=location__service__pb2.Empty.FromString,
                )
        self.AlarmStream = channel.unary_stream(
                '/LocationService.LocationService/AlarmStream',
                request_serializer=location__service__pb2.AlarmRequest.SerializeToString,
                response_deserializer=location__service__pb2.AlarmEvent.FromString,
                )


class LocationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PaligonCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PaligonDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PaligonList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PointCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PointDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PointList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutyCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutyStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutyList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DutyInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Location(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AlarmStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PaligonCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.PaligonCreate,
                    request_deserializer=location__service__pb2.PaligonRequest.FromString,
                    response_serializer=location__service__pb2.PaligonResponse.SerializeToString,
            ),
            'PaligonDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.PaligonDelete,
                    request_deserializer=location__service__pb2.PaligonDeleteRequest.FromString,
                    response_serializer=location__service__pb2.Empty.SerializeToString,
            ),
            'PaligonList': grpc.unary_unary_rpc_method_handler(
                    servicer.PaligonList,
                    request_deserializer=location__service__pb2.PaligonFilterRequest.FromString,
                    response_serializer=location__service__pb2.PaligonListResponse.SerializeToString,
            ),
            'PointCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.PointCreate,
                    request_deserializer=location__service__pb2.PointRequest.FromString,
                    response_serializer=location__service__pb2.PointResponse.SerializeToString,
            ),
            'PointDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.PointDelete,
                    request_deserializer=location__service__pb2.PointDeleteRequest.FromString,
                    response_serializer=location__service__pb2.Empty.SerializeToString,
            ),
            'PointList': grpc.unary_unary_rpc_method_handler(
                    servicer.PointList,
                    request_deserializer=location__service__pb2.PointListRequest.FromString,
                    response_serializer=location__service__pb2.PointListResponse.SerializeToString,
            ),
            'DutyCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.DutyCreate,
                    request_deserializer=location__service__pb2.DutyRequest.FromString,
                    response_serializer=location__service__pb2.DutyResponse.SerializeToString,
            ),
            'DutyStop': grpc.unary_unary_rpc_method_handler(
                    servicer.DutyStop,
                    request_deserializer=location__service__pb2.StopDutyRequest.FromString,
                    response_serializer=location__service__pb2.Empty.SerializeToString,
            ),
            'DutyList': grpc.unary_unary_rpc_method_handler(
                    servicer.DutyList,
                    request_deserializer=location__service__pb2.DutyListRequest.FromString,
                    response_serializer=location__service__pb2.DutyListResponse.SerializeToString,
            ),
            'DutyInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.DutyInfo,
                    request_deserializer=location__service__pb2.DutyInfoRequest.FromString,
                    response_serializer=location__service__pb2.DutyInfoResponse.SerializeToString,
            ),
            'Location': grpc.unary_unary_rpc_method_handler(
                    servicer.Location,
                    request_deserializer=location__service__pb2.LocationRequest.FromString,
                    response_serializer=location__service__pb2.Empty.SerializeToString,
            ),
            'AlarmStream': grpc.unary_stream_rpc_method_handler(
                    servicer.AlarmStream,
                    request_deserializer=location__service__pb2.AlarmRequest.FromString,
                    response_serializer=location__service__pb2.AlarmEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LocationService.LocationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LocationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PaligonCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LocationService.LocationService/PaligonCreate',
            location__service__pb2.PaligonRequest.SerializeToString,
            location__service__pb2.PaligonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PaligonDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LocationService.LocationService/PaligonDelete',
            location__service__pb2.PaligonDeleteRequest.SerializeToString,
            location__service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PaligonList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LocationService.LocationService/PaligonList',
            location__service__pb2.PaligonFilterRequest.SerializeToString,
            location__service__pb2.PaligonListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PointCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LocationService.LocationService/PointCreate',
            location__service__pb2.PointRequest.SerializeToString,
            location__service__pb2.PointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PointDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LocationService.LocationService/PointDelete',
            location__service__pb2.PointDeleteRequest.SerializeToString,
            location__service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PointList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LocationService.LocationService/PointList',
            location__service__pb2.PointListRequest.SerializeToString,
            location__service__pb2.PointListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DutyCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LocationService.LocationService/DutyCreate',
            location__service__pb2.DutyRequest.SerializeToString,
            location__service__pb2.DutyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DutyStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LocationService.LocationService/DutyStop',
            location__service__pb2.StopDutyRequest.SerializeToString,
            location__service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DutyList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LocationService.LocationService/DutyList',
            location__service__pb2.DutyListRequest.SerializeToString,
            location__service__pb2.DutyListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DutyInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LocationService.LocationService/DutyInfo',
            location__service__pb2.DutyInfoRequest.SerializeToString,
            location__service__pb2.DutyInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Location(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LocationService.LocationService/Location',
            location__service__pb2.LocationRequest.SerializeToString,
            location__service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AlarmStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/LocationService.LocationService/AlarmStream',
            location__service__pb2.AlarmRequest.SerializeToString,
            location__service__pb2.AlarmEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
